version: '3.8'

services:
  server:
    image: koshak04/tinkoff_academy:latest
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8000:8000"
  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1